-- MySQL Script generated by MySQL Workbench
-- Sun Sep 21 03:00:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taskpro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taskpro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taskpro` ;
USE `taskpro` ;

-- -----------------------------------------------------
-- Table `taskpro`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskpro`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `document` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskpro`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskpro`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `client_user_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `client_user_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `taskpro`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taskpro`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taskpro`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(155) NOT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `index3` () VISIBLE,
  INDEX `client_task_id_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `client_task_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `taskpro`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
